CHANGELOG.md
README.md
example/lib/main.dart
example/pubspec.lock
lib/pin_code_fields.dart
pubspec.yaml

I've done some refactoring to `_textEditingController`'s listener, calls `setState` only once, so it should have slightly better perfs
- renamed `currentText` to `onChanged`
- renamed `onComplete` to `onCompleted` to be in-line with the renaming done above
- Added a new constructor parameter called `enabled` because of the renaming of `currentText` and now being optional. Default is `true`
---
With the addition of `inputFormatters` when you paste an incorrect formatted text and then try to edit it, it'll reset the input.
**Example:**
Here I got `inputFormatters: [WhitelistingTextInputFormatter.digitsOnly]`
---
And the `onCompleted` seems like a useful feature, but it only triggers once when every fields are filled.
So, if you want to disable a `RaisedButton` only if the pins aren't …

:zap: better perfs, refactoring

---

lib/pin_code_fields.dart

Hiding the border of TextField and setting the textColor of it to transparent.
Removing the withOpacity(1) of backgroundColor to allow transparency.

Allow transparent backgroundColor

---

lib/pin_code_fields.dart

I am not quite sure why transparent background is not allowed. After going through the code, I found out the reason seems to be the underneath hidden textfield is showing its border. After setting the border to border none prevents it to happen when the background is transparent.

Allow transparent background

---

lib/pin_code_fields.dart

This fixes the following bug:
after tapping the PinCodeTextField, the keyboard opens, and then if the user presses the 'back' button, the keyboard closes but PinCodeTextField cannot be pressed again.

added short delay when refocusing

---

example/lib/main.dart
lib/pin_code_fields.dart

- [FIX] App crashes when clipboard is NULL. Ref issue #45 
- Added beforeTextPaste callback. That can validate text before pasting it. Ref #46.

Fix #45 & #46 - Paste text enhancement

---

lib/pin_code_fields.dart

This will guard the print statements behind the kReleaseMode constant.
Perhaps the print statements could be removed altogether?

Ensure print statements only run for debug builds

---

lib/src/pin_code_fields.dart
test/pin_code_fields_test.dart

Ensures the error animation stream subscription is cancelled when the widget is disposed.

Dispose error animation stream when widget is disposed

---

lib/src/pin_code_fields.dart

Fixed disabled border of invisible slide transition text form field visible when pins are disabled

---

lib/src/pin_code_fields.dart

Let Flutter handle the default colors.
Before/After:

Remove default text color and background color

---

README.md
example/lib/main.dart
lib/src/models/pin_theme.dart
lib/src/pin_code_fields.dart

This pull request contains a feature request from here: https://github.com/adar2378/pin_code_fields/issues/174
The current implementation changes both `activeColor` & `inactiveColor` when an error is triggered.
Usage is as simple as defining `errorBorderColor` in the `PinTheme`.

Implementation of errorBorderColor

---

lib/src/pin_code_fields.dart

[TextFormField](https://api.flutter.dev/flutter/material/TextFormField-class.html) has `scrollPadding` param, which is not provided in your implementation.

pass scrollPadding

---

lib/src/pin_code_fields.dart

This pull request solves `errorTextSpace` not used when manually validating issue:#228.
@adar2378

Solve errorTextSpace not used when manually validating issue:#228.

---

lib/src/pin_code_fields.dart

Hey there,
is there any reason the obscureText flag is not handed down to the TextFormField? - I had the problem, that my "obscured" textfields were showing a plaintext copy of the inserted PIN above the keyboard. So e.g. when I entered ABC as *** in the Widget, there was a suggestion shown for ios on the simulator and the device which contained the ABC as readable text. Pretty strange security related issue. While this issue seems to be a more general one. It seems to be solvable by setting the obscureText flag to true.
Maybe this has unwanted sideeffects im currently not aware of yet.
E.g. whenever i enter something with the obscureText flag active, I am presented with the "Keychain" Option in the suggestion bar...

optionally obscure text

---

lib/src/pin_code_fields.dart
test/pin_code_fields_test.dart

Hey, @adar2378 
Thanks for the lib!
Sometimes we don't need any callbacks on value changed (e.g. in the tests).
So, I suggest to make `onChanged` field nullable.

chore: make onChanged nullable

---

lib/src/models/pin_theme.dart
lib/src/pin_code_fields.dart

Hi, I would think that it's a good choice for the user to add box shadow for active/inactive pin code field instead of all pin code field. I have added two new fields(activeBoxShadow & inActiveBoxShadow) for Pin Theme. Thanks

added box shadow for active and inactive pin code field

---

lib/src/pin_code_fields.dart

Added ability to pass `onEditingComplete` parameter to `PinCodeTextField` constructor to be able to control automatic keyboard dismiss behavior.
In my app it's required for the keyboard to stay visible when users click "done/next" action on the keyboard during PIN code flow. At the moment, the keyboard will automatically close.
Here is a link to detailed explanation why `onEditingComplete` parameter actually helps:
https://stackoverflow.com/a/65172533/4903519
This change should not affect any existing code since `onEditingComplete` parameter is null by default.

Added ability to pass "onEditingComplete" parameter to PinCodeTextField

---

lib/src/pin_code_fields.dart

| With `Platform.iOS` | With `Platform.other` |
|---------------------|-----------------------|
| <img width="430" alt="Screenshot 2023-01-27 at 1 27 46 AM" src="https://user-images.githubusercontent.com/74326345/214939242-765fdc2e-b21c-46ac-9d0d-0647eca376a2.png"> | <img width="446" alt="Screenshot 2023-01-27 at 1 28 19 AM" src="https://user-images.githubusercontent.com/74326345/214939170-1cee3dd5-b3fd-4aa0-8caf-b8fdf762e73b.png"> |
resolves #318

fix: Platform.iOS does not show cupertino dialog

---

lib/src/pin_code_fields.dart
test/pin_code_fields_test.dart

- Unnecessary type casting casting
- PinCodeTextField is marked as `@immutable`, but one or more of its instance fields aren't final: _PinCodeTextField.onEditingComplete_
Formatted code according to dart standards

fix: linting and dart immutable issues

---

lib/src/pin_code_fields.dart

I fixed error border at TextFormField in  PinCodeTextField.
If inputDecoration of theme is setted, like under picture, unncessary error border is shown when validator is called.

fix:remove error-border from TextFormField

---

lib/pin_code_fields.dart
lib/src/models/dialog_config.dart
lib/src/models/pin_code_platform.dart
lib/src/models/platform.dart
lib/src/pin_code_fields.dart

- Changed enum name to `PinCodePlatform` from `Platform`
- Making `PinCodePlatform` part of `pin_code_fields` library ultimately exposing enum to direct use from import:
```dart
import 'package:pin_code_fields/pin_code_fields.dart';
```
- Added proper docs explaining the use of values from the `PinCodePlatform` enum
resolves #316, resolves #108

feat!: exposing platform enum to use directly

---

lib/src/models/pin_theme.dart
lib/src/pin_code_fields.dart

With PR #335 the option to add indidual borderWidths was added however the old borderWidth variable was not removed which makes it frustrating for people updating their versions. With this change we would allow the user to continue to use borderWidth to set the value of all individual widths but still be able to override it with the individual widths.

Border width as default
