adar2378/pin_code_fields

README.md, lib/pin_code_fields.dart
fix typo in negativeText param
=> fix typo in negativeText param

lib/pin_code_fields.dart
It would be nice if the appearance of the iOS keyboard could be
changeable with dark or light brightness.
=> Add keyboardAppearance property

lib/src/pin_code_fields.dart
=> Add the onSaved callback to work with `FormState.save`

example/lib/main.dart, lib/src/pin_code_fields.dart
Applies to this issue: https://github.com/adar2378/pin_code_fields/issues/84
=> Add the onTap callback for the pin_code form

lib/src/pin_code_fields.dart
=> added autofill feature introduced in flutter 1.20

example/lib/main.dart, lib/src/pin_code_fields.dart
=> Customizable paste text style

example/android/app/src/main/AndroidManifest.xml, example/ios/Runner/Info.plist, lib/src/pin_code_fields.dart
Allow pin code field to enable autofill service optionally.
=> Option to disable autofill service

README.md
Fixed tiny typo error in readme.md😊
=> Fixed tiny typo error in readme.md

example/lib/main.dart, lib/src/pin_code_fields.dart
=> Obscuring character

lib/src/pin_code_fields.dart
fixes #83 @adar2378 I have added the box-shadow field decoration container
=> added the Shadow in pincode

lib/src/pin_code_fields.dart
=> add fallback color for cursorColor

lib/src/pin_code_fields.dart
It's a PR for the issue https://github.com/adar2378/pin_code_fields/issues/143
=> Fixed a bug when setState is being called after dispose()

lib/src/pin_code_fields.dart
`obscureWidget` option added. 
Fixes #141
=> obscure widget

lib/src/pin_code_fields.dart
=> Haptic feedback

lib/src/pin_code_fields.dart
=> [issue #163] pass params for autofill group

lib/src/pin_code_fields.dart
Initial value taken into account if assigned to the TextEditingController
=> pin_code_fields/issues/153

lib/src/pin_code_fields.dart
fix this [bug](https://github.com/flutter/flutter/issues/71476) , and [issue](https://github.com/adar2378/pin_code_fields/issues/163)
=> feature, use external [AutoFillGroup] param

README.md, lib/src/pin_code_fields.dart
In this PR i added a feature to be able to set a hint or placeholder for the fields.
resolves: #161  #82 
https://user-images.githubusercontent.com/45693911/118806281-2a14fd80-b8a7-11eb-826e-15a45b0817df.mov
=> Add hint/placeholder feature

lib/pin_code_fields.dart, lib/src/gradiented.dart, lib/src/pin_code_fields.dart
Added ability to set text gradient (`textGradient` property)
=> Added ability to set text gradient (textGradient property)

lib/src/pin_code_fields.dart
solves: https://github.com/adar2378/pin_code_fields/issues/155
=> Resolved blinkDebounce setState() after dispose() bug.

lib/src/pin_code_fields.dart
Hi, @adar2378!
I have some problems with focus and tapping on fields. There is kind of a flicker when you tap on fields and the keyboard is hidden or shown weirdly fast.
I suppose it would be better to add an additional parameter to control unfocus when we manually invoke it in code.
https://github.com/adar2378/pin_code_fields/issues/238
https://user-images.githubusercontent.com/24309240/153844416-88686567-2cdb-4dd4-a7c1-34dde0d222ae.mp4
=> feat: autoUnfocus

lib/src/pin_code_fields.dart
Fixes issue #237 by adding an optional TextDirection and margin to add margins from left and/or right for example.
@adar2378
=>  fix issue #237

README.md, lib/src/pin_code_fields.dart
Hi @adar2378 
Thank you for this library!
Sometimes, we want to add separator in fields (e.g. https://github.com/adar2378/pin_code_fields/issues/270)
So, I suggested to add `separatorBuilder` field.
=> Added separator builder

example/windows/flutter/generated_plugins.cmake, lib/src/pin_code_fields.dart
fixed issue where setState() was being called through listener even after the Widget was unmounted.
=> Fix setState() called after dispose() Issue

example/lib/main.dart, lib/src/pin_code_fields.dart
Replacing deprecated code usage with the new recommended code introduced in `Flutter v3.7.0`
resolves #315
=> refactor: replaced deprecated classes

lib/src/models/dialog_config.dart
Increases readability and performance
=> refactor: using language `??` feature

lib/src/models/pin_theme.dart, lib/src/pin_code_fields.dart
feat: added individual width for the fields, allowing them to be use for highlight selected field
=> feat: added individual width for the fields

lib/src/pin_code_fields.dart
Fixes https://github.com/adar2378/pin_code_fields/issues/368
=> Add a boolean flag to allow showing/hiding the paste confirmation dialog
